### ISSUE TITLE
Windows notifications appear for messages YOU send

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-kotlin-ui#106]
**Task**

As per the image below, a user reported that the messages he sent were appearing as notifications:

![Image](https://github.com/stakwork/sphinx-kotlin-ui/assets/142233216/868febe1-7e04-4585-be61-6e66686a113f)

In the image, the user sent those message TO those users but he received the notifications

**Comment by tomsmith8** [comment]
@tomastiminskas I can bounty this out but unsure exactly where in the code to point the hunter to?

**Comment by tomastiminskas** [comment]
@tomsmith8 the logic to show the notification is inside the method of SphinxRepository:

https://github.com/stakwork/sphinx-kotlin-core/blob/213ff9ac2163b10d0510ac7d371187327f08125d/src/jvmMain/kotlin/chat/sphinx/features/repository/SphinxRepository.kt#L330

There a check needs to be added to avoid sending notification if it's a sent message instead of a received message

**Comment by okhot** [comment]
I can help fix this if it hasn't been fixed yet!

**Comment by tomsmith8** [comment]
@okhot any updates with this?

**Comment by tomsmith8** [comment]
This is now fixed
